# Soovitusi õppimiseks

\multicolsbegin

## Õpi õpetama!

Kui loed, vaatad või kuulad midagi või avastad kogemuslikult midagi, mis tekitab tunde, et said millestki aru, siis räägi see kohe läbi, nagu sa õpetaksid kedagi! Heal juhul sul ongi keegi, kellele saad seda kasvõi lihtsustatult seletada. Kui pole kedagi muud, kellele oma arusaamisest rääkida, siis kujuta ette ja räägi endale! Nii mõtled mõistetu uuesti läbi ja kinnistad.

## Õpi jupikaupa!

Iga jupi õppimise järel mõtle läbi, mida sa just õppisid! Nii et koorma sa end liiga suure hulga uue teabega, vaid jõuad väiksemates kogustes kinnistada.

## Eelista rääkimist!

Kui oled mingi jupi õppinud, räägi see endamisi läbi! Võid ka kirjutada, aga rääkimine pole nii piiratud kui kirjutamine. Kirjutamine kindlasti toetab, aga verbaalne seletus on ka vajalik.

## Korda eelnevaga!

Läksin juuli 2023 keskel üle dekaadi taas tantsutrenni. Õpetati järjest mitu kava. Vahel oli nädalas mitu trenni. Meelde jäi mulle ainult üks kava.
Augustis otsustasin hakata pärast igat tantsutrenni õpitud kavasid meenutama. Kui trennis õpetati mitut kava, püüdsin juba teise kava kestel meenutada eelmist ja ei meenunud midagi.
Olulisem oli püsida tsoonis ja õppida uut kava.

Kui trenn oli läbi, läksin puude alla ja tantsisin läbi esmalt viimase kava, et see mälust ei kaoks. Kui komponendid olid ununenud, tuletasin need meelde, kuni terve kava oli meeles. Seejärel meenutasin, milline oli eelviimane kava, ja tantsisin ka selle nii kaua läbi, kuni suutsin seda veatult teha. Nii meenutasin kõik kavad ja kombineerisin need kokku üheks koondkavaks, mida tantsisin nii kaua läbi, kuni suutsin kolm korda järjest veatult läbi tantsida. Seejärel läksin koju ja tantsisin koondkava uuesti läbi, misjärel oli keskpikas mälus nii umbes nädalaks see kava salvestatud.

Kui nädalas oli veel trenne, siis kordasin protseduuri ja liitsin uue koondkava eelmisega, nii et tulemuseks oli uus ja pikem koondkava. Kui mingis päevas tantsutrenni polnud, tantsisin koondkava ikkagi läbi. Nii tegin iga päev. Järgnevas nädalas oli vilumus piisav ja jäädvustasin kava audiovisuaalselt.

Seda õppimise meetodit saab kasutada mis tahes teema puhul. Sinul on igas koolipäevas mitme valdkonna kontaktsessioonid. Pärast kooli, kui oled kodus, võta endale aeg ja meenuta, mida õppisid, mida tegid viimases kontaktsessioonis! Seejärel meenuta järjest, mida varasemates sessioonides samas päevas tegid! Seejärel, kui sulle on jäetud midagi iseseisvaks tegemiseks, tegele sellega!

Järgmises koolipäevas tee samamoodi, aga meenuta ka eelmise päeva igas kontaktsessioonis õpitut! Kolmapäevas meenuta nii kolmapäeva, teisipäeva kui esmaspäeva kontaktsessioonides õpitut! Nii toimi esmaspäevast reedeni ja järelikult on reedes kõige rohkem meenutada. Laupäevas-pühapäevas vali eri sama nädala teemade seast välja midagi ja ühenda kokku luues iseendale ülesandeid! Niimoodi sa kinnistad piisavalt pikaks ajaks, mida koolis õpid, ja hiljem on lihtsam meenutada. Toimi niimoodi igas koolinädalas! Iga uus nädal algab nullist.

## Koge allikaid!

Kui loed kontaktsessioonis käsitletud peatüki pärast kontaktsessiooni iseseisvalt läbi, avastad uusi vaatenurki ja mida enam vaatenurki millelegi sul on, seda paremini teemat mõistad. Sama kehtib audiovisuaalsete teoste kogemise kohta.

## Harjuta!

Arusaamise kinnistamiseks on vaja kümnete teemakohaste ülesannete lahendamine. Kui lahendad mingi valemi kasutamise kohta piisavalt ülesandeid, on see valem sul juba meeles ja ei pea tuletama.

Alati saad ka kontrollida lahendit[@physics(lk A23-A46)]. Kui saad teistsuguse lahendi, võrdle enda lahenduskäiku minu omaga[@looduseuurimine] ja korrigeeri!

## Harjumused

*1-D Kinematics*'s[@a1dkinpacketpdf, lk 24] ja *Physics for Scientists Engineers*'s[@physics, lk 33] on esitatud arvutusprobleemide lahendamise harjumused, mille soovitan sul endas välja kujundada.

## Teabe rohkus

Inimene opereerib sellega, mis on tal peas. Mida rohkem sa tead ja oskad, seda rohkem lood sa endale võimalusi selle oskusteabe rakendamiseks. Seega emba igasugust teavet ja arvesta, et kunagi võib sellest üleskorjatud ja mõistetud teabest sulle kasu olla!
  

\multicolsend
